services:
  - type: web
    name: isikukood-kontroll
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: isikukood_db
          property: connectionString